
version: '3.1'

services:
  s_jenkins:
    container_name: c_jenkins
    image: salihcantekin/jenkinswithdocker
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins_file:/var/jenkins_home